name: Backup PostgreSQL

on:
  schedule:
    - cron: "0 3 * * *"  

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Go configs
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Dependencies install
        run: go mod tidy

      - name: Executar Backup
        run: go run backup.go
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
